jenkins:
  
  clouds:
    - docker:
        name: "docker"
        dockerApi:
          dockerHost:
            credentialsId: "aab15265-4f0a-46a0-8e97-66695bd3d312"
            uri: "tcp://192.168.178.41:2376"
          readTimeout: 60
        templates:
          - labelString: "docker-agent"
            dockerTemplateBase:
              image: "jenkinsci/slave:latest"
              pullCredentialsId: ''
              volumes:
                - hello:/hello
                - world:/world
              environmentsString: |
                hello=world
                foo=bar
            remoteFs: "/home/jenkins/agent"
            connector:
              attach:
                user: "jenkins"
            instanceCapStr: "10"     
  numExecutors: 1
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: false
  remotingSecurity:
    enabled: false
unclassified:
  location:
    url: "${JENKINS_HOST}"
security:
  globalJobDslSecurityConfiguration:
    useScriptSecurity: false

credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              scope: GLOBAL
              id: "github-token"
              username: "${GITHUB_USERNAME}"
              password: "${GITHUB_PASSWORD}"
              description: "GitHub Token"
          - string:
              scope: GLOBAL
              id: "slack-token"
              secret: "${SLACK_TOKEN}"
          - certificate:
            scope: SYSTEM
            id:       ssh_private_key
            password: ${SSH_KEY_PASSWORD}
            keyStoreSource:
              fileOnMaster:
                keyStoreFile: /docker/secret/id_rsa 
          - dockerServer:
              clientCertificate: |-
                -----BEGIN CERTIFICATE-----
                MIIFAzCCAuugAwIBAgIUJJ4c6ULU5iUW+isMG6ESjgJcsEEwDQYJKoZIhvcNAQEL
                BQAwTTELMAkGA1UEBhMCVVMxDTALBgNVBAgMBFRlc3QxDDAKBgNVBAcMA2ZvcjEN
                MAsGA1UECgwEVGVzdDESMBAGA1UEAwwJbG9jYWxob3N0MB4XDTE5MDgwODE3MTQy
                NVoXDTIwMDgwNzE3MTQyNVowETEPMA0GA1UEAwwGY2xpZW50MIICIjANBgkqhkiG
                9w0BAQEFAAOCAg8AMIICCgKCAgEAr0C9J4+yJai77fbawMaXWcyR+rOTNOiiWvC2
                ShMlH/tksN9L1j4WfqWSo6IpRlsIJNTE4Lzv7ZdnaTRM3tqamY9o50GjrAhTdxpY
                qUhlZFUO8z/0Jhdh3GeRJLFBF+XWHTEpH0oIDKIAyQHYg+3uzKIv5idQu0xn6uKI
                lyY0EOKPLynfSXBQHRdQy4yfAriUxbLPw2ELBw0ipOKPfE+XBdDSozKfS6wahzzz
                EeMCQJLOHqX/4AlyY2foVOS+18y4AVSs1rqqEthUy0uBRV84NnKrHz0gqe6JLGHs
                xCUfMsCgrLS+XXw8EZSBvr7InDWeUuRB7sNMFwEVUABKcboxkaXnsHjD2P1QBQME
                0MD4RMbX3SogQz7IDRrTHSE2/5RcDxPApwHzWPnTiEszyNInZMMzYpiuAUDF0Jbw
                oxqwhZ7+km95OkUABtnacFBbtf/3MXOLiZIIyKbhVFENC2KM0Jzuhn/zViSbVwcC
                6oi9RyUQMvbE6pVRQPGozBs78z9MJCdkuGmP7enISFAIqVdXATn9QBSUaIOOrZbc
                U2pj2ouc7oRAJ+5hx5sNgzXRNJoOXKCHo3SNRKwzkzclUNc8yAmo/xzdhvMjD8fL
                avpfTCwAPke/JSs+U2doO3FAMhZaldh3yHNJXmSqvMcYeN1wT3DC1+kqZ9M/+vwl
                tJrMC50CAwEAAaMXMBUwEwYDVR0lBAwwCgYIKwYBBQUHAwIwDQYJKoZIhvcNAQEL
                BQADggIBAAmzLb18Cnau9ENulyNtNlhGHuqqtYlTvoLH7eMoLfuncxi45LCTp7Hv
                C940xb8R9JvdNNloWcZNxOep27qNgDjXgXw9lu8JPJ7CClxHUBmIA5Xm10M72a4A
                ezr+ropaKS3jEuoWSO2xK4vvfGRiAUeZySiDDNneNQouHfILFYkjGYGqlyrwFtxL
                0k86nYiSADGdDy6owuOq91yJB4l8i+SIQLd7NT+dJKTIdCrS9QppJsMxUh9uyEYY
                tH3jxLqE3lFfgEfshDQ66qA5AQUtyM8NNGDA9gSn6MV72UEJGvLBQi3f8DBrh2f7
                zwOTW3Y/z/0K0bQQGFISdN6UXHhjSU5gSYkowDtpWyXPDLZdZqKGrrFKwAvVrdur
                00pUQQmwfCz3j1U5WpBs9vlVlQoWtyu163hL4dn2c7QRxqIeKwv6djdLJ0VRFI0N
                hMZsoM1V8qclf6l2fDhwNIVUmVRqe3p2KMjy8xBdjfCwZUJqzJwco4hFxcO4riHc
                ObRseHXT15+yinbXZipsKJCccIyDpfuUfLD2MlS74zKbMG2uSPbgfesQlWlH5jVo
                li1wlDqgri3M5f0cBKK0LUTGECyNW0e6CnY6g7ur+BNQIAznl9Y8x2sJcRwgYxDy
                FzDyCBtdpebbXAAbXZ2Wz5lwc0r5VIWRsXCrgt4Nwz41UkSofzGg
                -----END CERTIFICATE-----
              clientKeySecret: $(cat ${JENKINS_HOME}/.docker/key.pem) 
              description: "docker"
              id: "aab15265-4f0a-46a0-8e97-66695bd3d312"
              scope: GLOBAL
              serverCaCertificate: |-
                -----BEGIN CERTIFICATE-----
                MIIFezCCA2OgAwIBAgIUTWLPfODzdvJHBlnC8zIdxIaxKaMwDQYJKoZIhvcNAQEL
                BQAwTTELMAkGA1UEBhMCVVMxDTALBgNVBAgMBFRlc3QxDDAKBgNVBAcMA2ZvcjEN
                MAsGA1UECgwEVGVzdDESMBAGA1UEAwwJbG9jYWxob3N0MB4XDTE5MDgwODE3MTQy
                MloXDTE5MDkwNzE3MTQyMlowTTELMAkGA1UEBhMCVVMxDTALBgNVBAgMBFRlc3Qx
                DDAKBgNVBAcMA2ZvcjENMAsGA1UECgwEVGVzdDESMBAGA1UEAwwJbG9jYWxob3N0
                MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAxoiSpv1lNOOeYwv0e/bh
                y3AqVurVtns+JOjJQojn2jmG4Vzrfqjyc3xCX23MG+Qh/Y6vRTHwDcs0UY1cnFKJ
                YXt7ePkUTLbYBa8AVZ6p9m4p89VHDfmXXYnvvSKHdLbYuYISfj3htmi1uxYiXdv4
                fS4a6tIj5Sjz2diRxWsEineZnxfDywTWIQ091OD83St8GbF8gcuFLqpt+kfNPVGu
                FDm3L63SnBaWQqW6NchIOqAEz4kGNcPDUJaZZf4bbr2fPAJEg8fFnFYf/pbK/vRw
                ltlkLxWdOadScTAAp5feN3Opgm6qwqvIl1eDqs4ihayYxlSlQh8U4H6xrzbveQd0
                NqtaritAMceL4KcyHO4+Dx7b9zNEJyXGOqhMUjvBjh9MGPrAhA28fAKYl2c2xb8T
                0Xsw7me6Fybnw9BrBWMbcnkdQlMfrW1vx5zUab4/zqzPGxTiJpfCVTNEk61PlVu7
                pQ2aGr1/7J60yYjF7IiElQ2u/p2gmAQ//GDSv37zH7K5x4YkSTQ6DGjsSK/IeVbQ
                Po5D+Hy5BXdO9qgyyxUFwLVMKpWAj0iC5V3RH6jef3vFXWk92yP457+qTlvzy1jS
                27fXaQ3qDpGEWATeDyGEDhx5HDxsHhEOurNpZ+JA3DlZEr2aUh1p+0evPsq8P+h9
                KnaGtasR3MRAziPstwF28tsCAwEAAaNTMFEwHQYDVR0OBBYEFPZyGnZoMRSY5Ae5
                oBrHE1tvL2OPMB8GA1UdIwQYMBaAFPZyGnZoMRSY5Ae5oBrHE1tvL2OPMA8GA1Ud
                EwEB/wQFMAMBAf8wDQYJKoZIhvcNAQELBQADggIBAGa1z6+dEnZg93/KykzbYzzl
                YsNwwn7RMJ4CfrDJhinKQTCGn92hHO/zrhCuRBDnnwAfUmX9SiaxmJI/Y/lPuoaO
                dNTgPZFl8Im8JMiB+qixU95zFdxEg8ezX7v9eW0tmEnGfSpulxEdf5M9yGD7Pprx
                67fF3CPBM1rwxQna1Y+eUuGRlkeShRbXw3IBuehap2K1T+UX9vtemkkLel/Q78Qk
                xsZCeqmU/kzDYgRMPcofp4Pq5y4yeUP1/+8KrNvcHdDgVfUMxFG8ZSZkwObPgMwC
                wWHkNXPow+P2Nk2dtwlvuNKAZ5qpuMiV3lelbW16AE3MOox5OE0TOY0q6Pm5ex48
                PFe9f0A1xnIqZp8IhgFbSAjbKe2CkFqplY91FiZU3Q98qOAxOVyAs8WeOuqd0lBy
                vtKWE2l+WotQx2kiHtargTHxtImHgsVBcPMTFraXlbp2yUNOOJHqd2/wKQl1WAJ9
                nU18xAcTkirSkvlcZIZhGvAS65pb6FC5CG6HHslifz6XSaKQFLb1Ts8CKU+NWdDy
                DikJgz3ZypDHLD/blrP9GjGRt/lwlTNFICXDDANDRow98H6uw5U6hilbLVl9TL4b
                FqPcNMSCf4iUp2RxImEzTaK93zP5Mx50EvTX4DFeKohT3r/HR4DkARhqQuRIXgIE
                x7BNFlx0sc+m2ijy5FHd
                -----END CERTIFICATE-----   
jobs:
  - file: "/config-inline.groovy"
  # - file: "/config-inline-docker-cloud.groovy"
      
     