jenkins:
  numExecutors: 1
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: false
  remotingSecurity:
    enabled: false
unclassified:
  location:
    url: "${JENKINS_HOST}"
security:
  globalJobDslSecurityConfiguration:
    useScriptSecurity: false
credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              scope: GLOBAL
              id: "github-token"
              username: "${GITHUB_USERNAME}"
              password: "${GITHUB_PASSWORD}"
              description: "GitHub Token"
          - string:
              scope: GLOBAL
              id: "slack-token"
              secret: "${SLACK_TOKEN}"
jobs:
  - script: >
      pipelineJob("foo") {
           definition {
                  cpsScm { 
                      scm { 
                        git { 
                          github('${GITHUB_REPOSITORY}','https')
                        } 
                        branches('develop') 
                        scriptPath('JENKINSFILE') 
                        extensions { }  // required as otherwise it may try to tag the repo, which you may not want 
                      } 
                    } 
                  }
                }
     