jenkins:
  numExecutors: 1
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: false
  remotingSecurity:
    enabled: false
unclassified:
  location:
    url: "${JENKINS_HOST}"
security:
  globalJobDslSecurityConfiguration:
    useScriptSecurity: false
clouds:
  - docker:
      containerCap: 4
      dockerApi:
        connectTimeout: 3
        dockerHost:
          credentialsId: "aab15265-4f0a-46a0-8e97-66695bd3d312"
          uri: "tcp://192.168.178.41:2376"
        readTimeout: 60
      name: "docker.local"
      templates:
      - dockerTemplateBase:
          image: "jenkinsci/slave:latest"
          tty: true
        instanceCapStr: "4"
        labelString: "docker.local.jenkins.slave"
credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              scope: GLOBAL
              id: "github-token"
              username: "${GITHUB_USERNAME}"
              password: "${GITHUB_PASSWORD}"
              description: "GitHub Token"
          - string:
              scope: GLOBAL
              id: "slack-token"
              secret: "${SLACK_TOKEN}"
          - dockerServer:
              clientCertificate: |-
                -----BEGIN CERTIFICATE-----
                MIIFAzCCAuugAwIBAgIUJJ4c6ULU5iUW+isMG6ESjgJcsEEwDQYJKoZIhvcNAQEL
                BQAwTTELMAkGA1UEBhMCVVMxDTALBgNVBAgMBFRlc3QxDDAKBgNVBAcMA2ZvcjEN
                MAsGA1UECgwEVGVzdDESMBAGA1UEAwwJbG9jYWxob3N0MB4XDTE5MDgwODE3MTQy
                NVoXDTIwMDgwNzE3MTQyNVowETEPMA0GA1UEAwwGY2xpZW50MIICIjANBgkqhkiG
                9w0BAQEFAAOCAg8AMIICCgKCAgEAr0C9J4+yJai77fbawMaXWcyR+rOTNOiiWvC2
                ShMlH/tksN9L1j4WfqWSo6IpRlsIJNTE4Lzv7ZdnaTRM3tqamY9o50GjrAhTdxpY
                qUhlZFUO8z/0Jhdh3GeRJLFBF+XWHTEpH0oIDKIAyQHYg+3uzKIv5idQu0xn6uKI
                lyY0EOKPLynfSXBQHRdQy4yfAriUxbLPw2ELBw0ipOKPfE+XBdDSozKfS6wahzzz
                EeMCQJLOHqX/4AlyY2foVOS+18y4AVSs1rqqEthUy0uBRV84NnKrHz0gqe6JLGHs
                xCUfMsCgrLS+XXw8EZSBvr7InDWeUuRB7sNMFwEVUABKcboxkaXnsHjD2P1QBQME
                0MD4RMbX3SogQz7IDRrTHSE2/5RcDxPApwHzWPnTiEszyNInZMMzYpiuAUDF0Jbw
                oxqwhZ7+km95OkUABtnacFBbtf/3MXOLiZIIyKbhVFENC2KM0Jzuhn/zViSbVwcC
                6oi9RyUQMvbE6pVRQPGozBs78z9MJCdkuGmP7enISFAIqVdXATn9QBSUaIOOrZbc
                U2pj2ouc7oRAJ+5hx5sNgzXRNJoOXKCHo3SNRKwzkzclUNc8yAmo/xzdhvMjD8fL
                avpfTCwAPke/JSs+U2doO3FAMhZaldh3yHNJXmSqvMcYeN1wT3DC1+kqZ9M/+vwl
                tJrMC50CAwEAAaMXMBUwEwYDVR0lBAwwCgYIKwYBBQUHAwIwDQYJKoZIhvcNAQEL
                BQADggIBAAmzLb18Cnau9ENulyNtNlhGHuqqtYlTvoLH7eMoLfuncxi45LCTp7Hv
                C940xb8R9JvdNNloWcZNxOep27qNgDjXgXw9lu8JPJ7CClxHUBmIA5Xm10M72a4A
                ezr+ropaKS3jEuoWSO2xK4vvfGRiAUeZySiDDNneNQouHfILFYkjGYGqlyrwFtxL
                0k86nYiSADGdDy6owuOq91yJB4l8i+SIQLd7NT+dJKTIdCrS9QppJsMxUh9uyEYY
                tH3jxLqE3lFfgEfshDQ66qA5AQUtyM8NNGDA9gSn6MV72UEJGvLBQi3f8DBrh2f7
                zwOTW3Y/z/0K0bQQGFISdN6UXHhjSU5gSYkowDtpWyXPDLZdZqKGrrFKwAvVrdur
                00pUQQmwfCz3j1U5WpBs9vlVlQoWtyu163hL4dn2c7QRxqIeKwv6djdLJ0VRFI0N
                hMZsoM1V8qclf6l2fDhwNIVUmVRqe3p2KMjy8xBdjfCwZUJqzJwco4hFxcO4riHc
                ObRseHXT15+yinbXZipsKJCccIyDpfuUfLD2MlS74zKbMG2uSPbgfesQlWlH5jVo
                li1wlDqgri3M5f0cBKK0LUTGECyNW0e6CnY6g7ur+BNQIAznl9Y8x2sJcRwgYxDy
                FzDyCBtdpebbXAAbXZ2Wz5lwc0r5VIWRsXCrgt4Nwz41UkSofzGg
                -----END CERTIFICATE-----
              clientKeySecret: "{AQAAABAAAAywQk8G9wd0NTtzjSNUrgcfUHMMupEso9GplgyJ4ytNC94kbOeNifCJhcWi2Bu+g3MRM/sNqloAEDysMUrkU//E8r9vdyRS9M5uHygLMVqbaLmNDG8aTG1781IK1HVrVHDg1pAyLnlqk7D4raZJ5SW/TnD/PUWXeIgl/OudIliwhQ19Yjcezpwh2liJevmG7bqEpxRAqQrHOx8uxScySacK1+e61JEoDiWpJUDoxIjSD1/sz/JrsORCGONVxwK2dHoYEx3/Z10BISFSvuf85BmAgoHoPMFDUIvnHqtSqV+Z1syuN/sknuyJSLaj//SVI5MLmC4iZRGmTPg0t5dLbg5rrN+tsefH9UyD3sxMJtKD37iaHcrUetmpm1NIm8Raof1/XxykSmJKqKkOUrdi2ala4CaaR/ywyRY+tkPLX1lfHk3Am4dwdGrK4OGi6ckveyNYkFPWe9Qvv08tSTVqI2UlH0v8krwum0PAixN0FeKweXZ261ZX+8w7ylmvm5oPavqpV5Djnpk4r4NE36w+dhnS+jYp6tTN16xbM3mJ2DCZ4ynJrr6/xrG7R/iftivRtKQvda5fb0Mplb79hz9Un4ptvO00C+A1ISFCLA+CaPaN25c10rpOfiihPhOIoH7g+cVUbDxQf1CEPxn6BjGnkWBe+GmgSo9xCd5G/tA+lfUov10KQCwYDcZdbRjP5Z0SJD3Tzw3iBPqyLnH+0LI8CYfvTLtFrFHZefbm54MM3mg3CqJdhSJwt48jvcFEYNJ6cLrKtZ7q36mqWqJQizZbkTxNrE/DxOU8qoj97FzBK4lMciLBvQB95PnC5DEkTiCA+od5jdO6Ynm822462qreOjspuaM8QXfhm2hXCudw82SqOX3Og3xD6QWNMJCHGiUagWd5Aq6CFOdDFjU3Gqg685/ggM0Z7+/fjqoVKdfAdGgfwjm0RDvTmVaC5x+CUpRPF1rPv2FMN/Nr2wG1sWglY4Yga+DxK6sijOTU0XjX79p5s4wwC3ndP3aFdny1kWcz0DmmyT2ncFvS7M6oDiMBUQcWraLYrdnkBcTo7moE0fjJX2V0fSBIDf8hRuhmUxx/a98jrqZA8ORT41618S5AIe3VF5eR0reXuMnd6RwWu+t3J1l7ofGK5qpT2l0VY02KScMsUANHRtFtJ0MUqo20A2iC/+LsyMONTk6QGKoPaKWvU/fwKrSpVrkEDcxf/2Jy0o+WwrXg9bDxUZaSQLgxNTEnMaeSnNTdGzPMgnwAS8swhu7ZjkaUrynup6Q2h/73xvYZBq8r5mqnq2dYF7tWweGxmWvKvockrmAXIKBE0A8OKRZZfCCK5PT3FD5gKeR0hjNpC/eB3jwHD2p0RsVK1DJdy6RxM4t9buZQOpd+f/gp/3JGpuOYfwg1oNNIe0eE4FD/rhX6rzjnd4kvnutFE8QGgB2AyAb01ogwIVsq3YESDg8+Rj6WZH33bWaydum+QpZNnXewXTLQR5DEo8oXEi2kD1+7cJ0WSVicx7Lnz4+OC2GoZXiwaVozdZRiasZlf4mSTDe7VRooQs52nlD1DkFQKfVvycr+08bqkGtUjlYwV2i0cGw8RgzL6rSz5Fc//tIqBzzak6YA/pDHyZFk1Ol3p7Hq6YhXriFZMtNwgMeZRJ5gp7OshLoOzTJoKlYVpnzcw1BObf5DDM93PwsGdfanKvmuH7FymYOP5WR+0dqQqRsY94HlcvQNHbUUoHoydalhylJfl6Uuge0/GPsZg6gAUhbICfOd9h+2lMF2Z1CB+QS2vap4MTXAQapZ3xP+ltif6lIpwz1cfYBznG2/WYnpddKnQdx9LksIhcLcISSPjU1rHP3SFrptP0VZvFvzTXCgHN8DZfkPqlr84jqzEQlSZ+uSI02Nc+dlZziRq1lhfhGx/5of5MIZXhrHjkgEkL4fVgbvQstF4690HfWHOElsAjTVAArrqn2y+NTVgwjUUdggy9Far6AXQaiWHYiOuZhoY2Tt3vwfL1WcL4Hw8fPNlbD4/ttprtd6P5n7C20Qadjji8QO8QAsfiW2BTV837r2syL7csUlBu0mXGl9GwXOl+wmR+ZnqpErSUdMTSiHzYwzFUKA+JvG/Ur4mlzedXukTTKglmeiJx7TMP1++Xq14QzVuJxKfWVZBV1a8evQBJHLzJuU/d7qDCD1wAyuJARMsr20iAfNh+fc6sE7UZMfVEElSz5dT6FSIiO4cIyC9R18E7DhGicGUT2CQZoGIEjwJTB/VdZ/HSapw0ZTZ8We1XLfYu9RUwD4t3v+to7XC16gHtbcPEJP1pKA4NY2mHfifyYnGt1roQEYLqOtqQG8GL76ZzL+gSFIESZSq8gBA5YzjJqHul7Qwyzl8LFDnRej1hGr6RsPWqE21pYP4RydVVX7JZ44/8auBkoQSZbv4JjyHn/ScbaY8xRH0PXmgyK8ZKjzDQ+nMYOGqNLGGscZ4+9R9GEGq0NdrdbgFSAPO5x88Ep+pxWWGxuffNNNExRcC2SVUgehvpi+Urz55iPhmfB1Un2b0E+unJoQqNkcytjTgmb7g8yRurO84dB0+y+Ax3DsJBsFxgG6+0CxL4APdA9ORcW4EDrv6XZZ3rloVu3UUINcGFH/Vh0L4x96NS3ughHNTPNg6MBvytI9EyWwDIypWzvKloFRzar3IkaPwfDOwtkSeuKoS6RnRqFjnK9O8PhMGfX6AqDvR6B0EHm0YIJcxsyUiC9U0W96wLsZkkLNCnOQNrd5y+b5A2f9n1oEtBpkXtFhXmOQ0SjmTZKTneAY7hhn5M732VvA1766NuEDw7dghkq3ciNg6h/exVmQ0QKIiVagwzORxBjD5didnmgru5W8pq47R4aZifI4ZVgphuwkWk9uTab8EH6RGbnzMA/BRQf0VLwuQiuY30fcKAy6MwozLn3ILz3Bq4v22on1b48fVx82Nw9sYTRiFznb9p6DxvN1WqNYO9gx4gs6Wq1rIyLZHPNBQsYNiRZTlqhq35NZsc5rNURm3lPex9RI2gPj3ZZ+OWKOXBxJEci/WZvJh67OvycRxb8rW+fzoUPAyoeeK4CLwHA+za6+L0GasFV3/eCGJ/L5r5OcjGkwi7ehD224+EJzsUMTGk0g3zao2cKpVCogFAhHXq+YpTxE5T/V1nxWwt+hnTz2YJ5d+LkiD8gRMPhBKkuRf1d86sNgFZ1JcNx3cTdyZ7Zuq7dIscWzVWmECqkJkWNWDkjZMBgiOzkDjJLGBW/r7Uk+k/9iEKtdQrjz5Szx8iBYiejBviFHOy9v/pnWnkuIK6EjKuILU3ctCd3trw/JjfgAX80y9FBJkDGyvXHTiEtYRZzeycXl1cd9fuMgEsgh536TDjRI/jSInhhyuWwAFgWz78weSr6mJ59QWGZil4TPUeak9jDCEHa+BiLY5rZ7hXYHIIARUADPuYBQ05ECJoNskgnOTVMeLLzMhipA2q4rkg/Fz+epJoBkxXHTcr7O3R7pxt1oJHuATOh2Oq8TwOTpSOUk+d+eIpuuggiD0ufTNCo/RKe1OsR9SiZkWfjX+JngcUOI+tVN5IBkGaJu9oUEzh/Z9ZiP/MUU8b3NF+GNjiSAdlQWZ4l6Qp6WdOpJNGoL1SxYeP0zGe2Xsmafe3I+7fFNTcX1+amNasW7olNS1ywHYSwCGZo314aZQkI/Sn38Y66HAE3WT4yOfTYOh8FA0B9xAw3a07ACC271D+aS/09+h4RDWCTEwTWifm1dfNAN4lri5/8oVf6z7UgWRFl3JsRuunSJYIHeftA+NEFi3Deat/h1JQMQOdU4YKfLflWTszbpSXAHWf9lxIgCfgKWv8zLFUBcZK2PYE4/g5F6nyLw1dsdYvd2rJpfSZdInftpVJe7j3JhV6kdUKCTUz3BwjFCD/O9m+PK9O4Nb/mLng9dwxWOtGTacAXOwUJjkZNpAFSKQ+/q4zetTi04ZYww5j1rX8H9XJ2JEPqS78LqqMD8tOU6ipJ8+91Uln+vf7KSu+ss9yXEs0RCUN3KWl/QFUu9Le22qM+kUQpwPAnVn6ppRxY5liLkEeZUZJS7vE2oFzKCMnPeN3M1KRxsLqDWnH1tFOck2+F5+MeRm8nFJdq+A/giSM29LdhkPF24zebnvutoFB0dL/rJI2JP5kVH9Xhsiv5gjjBJVeTyADD2xlASUebygCGgidOHyIAYRoatOGxeBPpkbDM2G12Aej4UxXOSwdtxN1e1/fK3VFT/D3TxU6H9NZesM6HY877one1L1JxKumsbj+VALgFtlta5Uz95NFT6tNXp8QutgOg784Tt9GkfrCyjoS8PpSzpfQwr6WI4Cx6Hh6hg8GqeTnZOyjsQw501CgDrF0vQm1IMK53o}"
              description: "docker"
              id: "aab15265-4f0a-46a0-8e97-66695bd3d312"
              scope: GLOBAL
              serverCaCertificate: |-
                -----BEGIN CERTIFICATE-----
                MIIFezCCA2OgAwIBAgIUTWLPfODzdvJHBlnC8zIdxIaxKaMwDQYJKoZIhvcNAQEL
                BQAwTTELMAkGA1UEBhMCVVMxDTALBgNVBAgMBFRlc3QxDDAKBgNVBAcMA2ZvcjEN
                MAsGA1UECgwEVGVzdDESMBAGA1UEAwwJbG9jYWxob3N0MB4XDTE5MDgwODE3MTQy
                MloXDTE5MDkwNzE3MTQyMlowTTELMAkGA1UEBhMCVVMxDTALBgNVBAgMBFRlc3Qx
                DDAKBgNVBAcMA2ZvcjENMAsGA1UECgwEVGVzdDESMBAGA1UEAwwJbG9jYWxob3N0
                MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAxoiSpv1lNOOeYwv0e/bh
                y3AqVurVtns+JOjJQojn2jmG4Vzrfqjyc3xCX23MG+Qh/Y6vRTHwDcs0UY1cnFKJ
                YXt7ePkUTLbYBa8AVZ6p9m4p89VHDfmXXYnvvSKHdLbYuYISfj3htmi1uxYiXdv4
                fS4a6tIj5Sjz2diRxWsEineZnxfDywTWIQ091OD83St8GbF8gcuFLqpt+kfNPVGu
                FDm3L63SnBaWQqW6NchIOqAEz4kGNcPDUJaZZf4bbr2fPAJEg8fFnFYf/pbK/vRw
                ltlkLxWdOadScTAAp5feN3Opgm6qwqvIl1eDqs4ihayYxlSlQh8U4H6xrzbveQd0
                NqtaritAMceL4KcyHO4+Dx7b9zNEJyXGOqhMUjvBjh9MGPrAhA28fAKYl2c2xb8T
                0Xsw7me6Fybnw9BrBWMbcnkdQlMfrW1vx5zUab4/zqzPGxTiJpfCVTNEk61PlVu7
                pQ2aGr1/7J60yYjF7IiElQ2u/p2gmAQ//GDSv37zH7K5x4YkSTQ6DGjsSK/IeVbQ
                Po5D+Hy5BXdO9qgyyxUFwLVMKpWAj0iC5V3RH6jef3vFXWk92yP457+qTlvzy1jS
                27fXaQ3qDpGEWATeDyGEDhx5HDxsHhEOurNpZ+JA3DlZEr2aUh1p+0evPsq8P+h9
                KnaGtasR3MRAziPstwF28tsCAwEAAaNTMFEwHQYDVR0OBBYEFPZyGnZoMRSY5Ae5
                oBrHE1tvL2OPMB8GA1UdIwQYMBaAFPZyGnZoMRSY5Ae5oBrHE1tvL2OPMA8GA1Ud
                EwEB/wQFMAMBAf8wDQYJKoZIhvcNAQELBQADggIBAGa1z6+dEnZg93/KykzbYzzl
                YsNwwn7RMJ4CfrDJhinKQTCGn92hHO/zrhCuRBDnnwAfUmX9SiaxmJI/Y/lPuoaO
                dNTgPZFl8Im8JMiB+qixU95zFdxEg8ezX7v9eW0tmEnGfSpulxEdf5M9yGD7Pprx
                67fF3CPBM1rwxQna1Y+eUuGRlkeShRbXw3IBuehap2K1T+UX9vtemkkLel/Q78Qk
                xsZCeqmU/kzDYgRMPcofp4Pq5y4yeUP1/+8KrNvcHdDgVfUMxFG8ZSZkwObPgMwC
                wWHkNXPow+P2Nk2dtwlvuNKAZ5qpuMiV3lelbW16AE3MOox5OE0TOY0q6Pm5ex48
                PFe9f0A1xnIqZp8IhgFbSAjbKe2CkFqplY91FiZU3Q98qOAxOVyAs8WeOuqd0lBy
                vtKWE2l+WotQx2kiHtargTHxtImHgsVBcPMTFraXlbp2yUNOOJHqd2/wKQl1WAJ9
                nU18xAcTkirSkvlcZIZhGvAS65pb6FC5CG6HHslifz6XSaKQFLb1Ts8CKU+NWdDy
                DikJgz3ZypDHLD/blrP9GjGRt/lwlTNFICXDDANDRow98H6uw5U6hilbLVl9TL4b
                FqPcNMSCf4iUp2RxImEzTaK93zP5Mx50EvTX4DFeKohT3r/HR4DkARhqQuRIXgIE
                x7BNFlx0sc+m2ijy5FHd
                -----END CERTIFICATE-----   
jobs:
  - file: "/config-inline.groovy"
  # - file: "/config-inline-docker-cloud.groovy"
      
     