version: '3.4'
services:
    jenkins:
        build: 
          context: .
          dockerfile: Dockerfile
        image: stadler/jenkins-org-plus-docker:latest
        tty: true
        stdin_open: true
        env_file:
            - jenkins.env
        volumes:
            - ./config.yml:/var/jenkins_casc.yml
            - ./config-inline.groovy:/config-inline.groovy
            - ./config-inline-docker-cloud.groovy:/config-inline-docker-cloud.groovy
            - ./add-docker-cloud.groovy:/var/jenkins_home/workspace/add-docker-cloud.groovy

        ports:
            - "8080:8080"
        environment:
            - DOCKER_HOST_IP="${DOCKER_HOST_IP}"
            - DOCKER_HOST_PORT=${DOCKER_HOST_PORT}"
            - DOCKER_HOST=tcp://${DOCKER_HOST_IP}:${DOCKER_HOST_PORT}
            - GITHUB_REPOSITORY=${GITHUB_REPOSITORY}
            - GITHUB_REPOSITORY_NAME=${GITHUB_REPOSITORY_NAME}
            - GITHUB_URL=${GITHUB_URL}

        secrets:
            - docker-ca.pem
            - docker-cert.pem
            - docker-key.pem
           

secrets:
  docker-ca.pem:
    file: "~/.docker/ca.pem"
  docker-cert.pem:
    file: "~/.docker/cert.pem"
  docker-key.pem:
    file: "~/.docker/key.pem"